api_url: http://localhost:8090/api/v1

region:
  name: dev
  id: dev

cluster:
  name: dev-cluster-1
  lb_addresses:
    - address: "127.0.0.1"
  config:
    stalwart_url: "http://hosting-stalwart:8080"
    stalwart_token: "dev-token"
    mail_hostname: "mail.hosting.localhost"
    docker_network: "hosting_default"
    haproxy_container: "hosting-haproxy"
  spec:
    shards:
      - name: web-1
        role: web
        node_count: 2
      - name: db-1
        role: database
        node_count: 1
      - name: dns-1
        role: dns
        node_count: 1
      - name: valkey-1
        role: valkey
        node_count: 1
    infrastructure:
      haproxy: false
      service_db: false
      valkey: false

node_profiles:
  - name: web-node
    role: web
    image: registry.localhost:5000/hosting/web-node:latest
    privileged: true
    network_mode: bridge
    ports:
      - { host: 0, container: 80 }
      - { host: 0, container: 443 }
      - { host: 0, container: 9090 }
    resources:
      memory_mb: 512
      cpu_shares: 1024
    health_check:
      test: ["CMD", "curl", "-f", "http://localhost:9090/health"]
      interval: "10s"
      timeout: "5s"
      retries: 3

  - name: db-node
    role: database
    image: registry.localhost:5000/hosting/db-node:latest
    privileged: false
    network_mode: bridge
    env:
      MYSQL_ROOT_PASSWORD: "rootpassword"
    ports:
      - { host: 0, container: 3306 }
      - { host: 0, container: 9090 }
    resources:
      memory_mb: 512
      cpu_shares: 1024
    health_check:
      test: ["CMD", "curl", "-f", "http://localhost:9090/health"]
      interval: "10s"
      timeout: "5s"
      retries: 5

  - name: dns-node
    role: dns
    image: registry.localhost:5000/hosting/dns-node:latest
    privileged: false
    network_mode: bridge
    env:
      PDNS_API_KEY: "secret"
      PDNS_GPGSQL_HOST: "hosting-service-db"
      PDNS_GPGSQL_PORT: "5432"
      PDNS_GPGSQL_DBNAME: "hosting_service"
      PDNS_GPGSQL_USER: "hosting"
      PDNS_GPGSQL_PASSWORD: "hosting"
    ports:
      - { host: 0, container: 53 }
      - { host: 0, container: 9090 }
    resources:
      memory_mb: 256
      cpu_shares: 512
    health_check:
      test: ["CMD", "curl", "-f", "http://localhost:9090/health"]
      interval: "10s"
      timeout: "5s"
      retries: 3

  - name: valkey-node
    role: valkey
    image: registry.localhost:5000/hosting/valkey-node:latest
    privileged: false
    network_mode: bridge
    ports:
      - { host: 0, container: 6379 }
      - { host: 0, container: 9090 }
    resources:
      memory_mb: 256
      cpu_shares: 512
    health_check:
      test: ["CMD", "curl", "-f", "http://localhost:9090/health"]
      interval: "10s"
      timeout: "5s"
      retries: 3

hosts:
  - hostname: localhost
    ip_address: "127.0.0.1"
    docker_host: "unix:///var/run/docker.sock"
    capacity:
      max_nodes: 10
    roles: [web, database, dns]
