# Auto-generated by Terraform. Do not edit manually.
api_url: http://localhost:8090/api/v1

region:
  name: dev
  id: dev

cluster:
  name: vm-cluster-1
  provisioner: external
  lb_addresses:
    - address: "${gateway_ip}"
  config:
    stalwart_url: "http://${gateway_ip}:8082"
    stalwart_token: "dev-token"
    mail_hostname: "mail.hosting.localhost"
  spec:
    shards:
%{ for node in nodes ~}
%{ if node.role == "web" && endswith(node.name, "node-0") ~}
      - name: ${node.shard_name}
        role: web
        node_count: ${length([for n in nodes : n if n.shard_name == node.shard_name])}
%{ endif ~}
%{ if node.role == "database" && endswith(node.name, "node-0") ~}
      - name: ${node.shard_name}
        role: database
        node_count: ${length([for n in nodes : n if n.shard_name == node.shard_name])}
%{ endif ~}
%{ if node.role == "dns" && endswith(node.name, "node-0") ~}
      - name: ${node.shard_name}
        role: dns
        node_count: ${length([for n in nodes : n if n.shard_name == node.shard_name])}
%{ endif ~}
%{ if node.role == "valkey" && endswith(node.name, "node-0") ~}
      - name: ${node.shard_name}
        role: valkey
        node_count: ${length([for n in nodes : n if n.shard_name == node.shard_name])}
%{ endif ~}
%{ endfor ~}
    infrastructure:
      haproxy: false
      service_db: false
      valkey: false

  external_nodes:
%{ for node in nodes ~}
    - id: ${node.id}
      shard_name: ${node.shard_name}
      ip_address: "${node.ip}"
%{ endfor ~}

node_profiles:
  - name: web-node
    role: web
    image: "unused-for-external"
    privileged: true
    resources:
      memory_mb: 1024
      cpu_shares: 2048

  - name: db-node
    role: database
    image: "unused-for-external"
    resources:
      memory_mb: 1024
      cpu_shares: 2048

  - name: dns-node
    role: dns
    image: "unused-for-external"
    resources:
      memory_mb: 512
      cpu_shares: 512

  - name: valkey-node
    role: valkey
    image: "unused-for-external"
    resources:
      memory_mb: 512
      cpu_shares: 512
