# Auto-generated by Terraform. Do not edit manually.
api_url: http://localhost:8090/api/v1
api_key: hst_dev_e2e_test_key_00000000

region:
  name: dev
  id: dev

cluster:
  name: vm-cluster-1
  lb_addresses:
    - address: "${gateway_ip}"
  config:
    haproxy_admin_addr: "localhost:9999"
    stalwart_url: "http://${gateway_ip}:8082"
    stalwart_token: "dev-token"
    mail_hostname: "mail.hosting.localhost"
  spec:
    shards:
%{ for node in nodes ~}
%{ if node.role == "web" && endswith(node.name, "node-0") ~}
      - name: ${node.shard_name}
        role: web
        node_count: ${length([for n in nodes : n if n.shard_name == node.shard_name])}
%{ endif ~}
%{ if node.role == "database" && endswith(node.name, "node-0") ~}
      - name: ${node.shard_name}
        role: database
        node_count: ${length([for n in nodes : n if n.shard_name == node.shard_name])}
%{ endif ~}
%{ if node.role == "dns" && endswith(node.name, "node-0") ~}
      - name: ${node.shard_name}
        role: dns
        node_count: ${length([for n in nodes : n if n.shard_name == node.shard_name])}
%{ endif ~}
%{ if node.role == "valkey" && endswith(node.name, "node-0") ~}
      - name: ${node.shard_name}
        role: valkey
        node_count: ${length([for n in nodes : n if n.shard_name == node.shard_name])}
%{ endif ~}
%{ if node.role == "storage" && endswith(node.name, "node-0") ~}
      - name: ${node.shard_name}
        role: storage
        node_count: ${length([for n in nodes : n if n.shard_name == node.shard_name])}
%{ endif ~}
%{ if node.role == "dbadmin" && endswith(node.name, "node-0") ~}
      - name: ${node.shard_name}
        role: dbadmin
        node_count: ${length([for n in nodes : n if n.shard_name == node.shard_name])}
%{ endif ~}
%{ endfor ~}
    infrastructure:
      haproxy: false
      powerdns: false
      valkey: false

  nodes:
%{ for node in nodes ~}
    - id: ${node.id}
      shard_name: ${node.shard_name}
      ip_address: "${node.ip}"
%{ endfor ~}
