// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: agent/v1/agent.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeAgent_CreateTenant_FullMethodName         = "/agent.v1.NodeAgent/CreateTenant"
	NodeAgent_UpdateTenant_FullMethodName         = "/agent.v1.NodeAgent/UpdateTenant"
	NodeAgent_SuspendTenant_FullMethodName        = "/agent.v1.NodeAgent/SuspendTenant"
	NodeAgent_UnsuspendTenant_FullMethodName      = "/agent.v1.NodeAgent/UnsuspendTenant"
	NodeAgent_DeleteTenant_FullMethodName         = "/agent.v1.NodeAgent/DeleteTenant"
	NodeAgent_CreateWebroot_FullMethodName        = "/agent.v1.NodeAgent/CreateWebroot"
	NodeAgent_UpdateWebroot_FullMethodName        = "/agent.v1.NodeAgent/UpdateWebroot"
	NodeAgent_DeleteWebroot_FullMethodName        = "/agent.v1.NodeAgent/DeleteWebroot"
	NodeAgent_ConfigureRuntime_FullMethodName     = "/agent.v1.NodeAgent/ConfigureRuntime"
	NodeAgent_ReloadNginx_FullMethodName          = "/agent.v1.NodeAgent/ReloadNginx"
	NodeAgent_CreateDatabase_FullMethodName       = "/agent.v1.NodeAgent/CreateDatabase"
	NodeAgent_DeleteDatabase_FullMethodName       = "/agent.v1.NodeAgent/DeleteDatabase"
	NodeAgent_CreateDatabaseUser_FullMethodName   = "/agent.v1.NodeAgent/CreateDatabaseUser"
	NodeAgent_UpdateDatabaseUser_FullMethodName   = "/agent.v1.NodeAgent/UpdateDatabaseUser"
	NodeAgent_DeleteDatabaseUser_FullMethodName   = "/agent.v1.NodeAgent/DeleteDatabaseUser"
	NodeAgent_CreateValkeyInstance_FullMethodName = "/agent.v1.NodeAgent/CreateValkeyInstance"
	NodeAgent_DeleteValkeyInstance_FullMethodName = "/agent.v1.NodeAgent/DeleteValkeyInstance"
	NodeAgent_CreateValkeyUser_FullMethodName     = "/agent.v1.NodeAgent/CreateValkeyUser"
	NodeAgent_UpdateValkeyUser_FullMethodName     = "/agent.v1.NodeAgent/UpdateValkeyUser"
	NodeAgent_DeleteValkeyUser_FullMethodName     = "/agent.v1.NodeAgent/DeleteValkeyUser"
	NodeAgent_InstallCertificate_FullMethodName   = "/agent.v1.NodeAgent/InstallCertificate"
	NodeAgent_HealthCheck_FullMethodName          = "/agent.v1.NodeAgent/HealthCheck"
)

// NodeAgentClient is the client API for NodeAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeAgentClient interface {
	// Tenant management
	CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*CreateTenantResponse, error)
	UpdateTenant(ctx context.Context, in *UpdateTenantRequest, opts ...grpc.CallOption) (*UpdateTenantResponse, error)
	SuspendTenant(ctx context.Context, in *SuspendTenantRequest, opts ...grpc.CallOption) (*SuspendTenantResponse, error)
	UnsuspendTenant(ctx context.Context, in *UnsuspendTenantRequest, opts ...grpc.CallOption) (*UnsuspendTenantResponse, error)
	DeleteTenant(ctx context.Context, in *DeleteTenantRequest, opts ...grpc.CallOption) (*DeleteTenantResponse, error)
	// Webroot management
	CreateWebroot(ctx context.Context, in *CreateWebrootRequest, opts ...grpc.CallOption) (*CreateWebrootResponse, error)
	UpdateWebroot(ctx context.Context, in *UpdateWebrootRequest, opts ...grpc.CallOption) (*UpdateWebrootResponse, error)
	DeleteWebroot(ctx context.Context, in *DeleteWebrootRequest, opts ...grpc.CallOption) (*DeleteWebrootResponse, error)
	// Runtime management
	ConfigureRuntime(ctx context.Context, in *ConfigureRuntimeRequest, opts ...grpc.CallOption) (*ConfigureRuntimeResponse, error)
	ReloadNginx(ctx context.Context, in *ReloadNginxRequest, opts ...grpc.CallOption) (*ReloadNginxResponse, error)
	// Database management
	CreateDatabase(ctx context.Context, in *CreateDatabaseRequest, opts ...grpc.CallOption) (*CreateDatabaseResponse, error)
	DeleteDatabase(ctx context.Context, in *DeleteDatabaseRequest, opts ...grpc.CallOption) (*DeleteDatabaseResponse, error)
	CreateDatabaseUser(ctx context.Context, in *CreateDatabaseUserRequest, opts ...grpc.CallOption) (*CreateDatabaseUserResponse, error)
	UpdateDatabaseUser(ctx context.Context, in *UpdateDatabaseUserRequest, opts ...grpc.CallOption) (*UpdateDatabaseUserResponse, error)
	DeleteDatabaseUser(ctx context.Context, in *DeleteDatabaseUserRequest, opts ...grpc.CallOption) (*DeleteDatabaseUserResponse, error)
	// Valkey management
	CreateValkeyInstance(ctx context.Context, in *CreateValkeyInstanceRequest, opts ...grpc.CallOption) (*CreateValkeyInstanceResponse, error)
	DeleteValkeyInstance(ctx context.Context, in *DeleteValkeyInstanceRequest, opts ...grpc.CallOption) (*DeleteValkeyInstanceResponse, error)
	CreateValkeyUser(ctx context.Context, in *CreateValkeyUserRequest, opts ...grpc.CallOption) (*CreateValkeyUserResponse, error)
	UpdateValkeyUser(ctx context.Context, in *UpdateValkeyUserRequest, opts ...grpc.CallOption) (*UpdateValkeyUserResponse, error)
	DeleteValkeyUser(ctx context.Context, in *DeleteValkeyUserRequest, opts ...grpc.CallOption) (*DeleteValkeyUserResponse, error)
	// SSL
	InstallCertificate(ctx context.Context, in *InstallCertificateRequest, opts ...grpc.CallOption) (*InstallCertificateResponse, error)
	// Health
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type nodeAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeAgentClient(cc grpc.ClientConnInterface) NodeAgentClient {
	return &nodeAgentClient{cc}
}

func (c *nodeAgentClient) CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*CreateTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTenantResponse)
	err := c.cc.Invoke(ctx, NodeAgent_CreateTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) UpdateTenant(ctx context.Context, in *UpdateTenantRequest, opts ...grpc.CallOption) (*UpdateTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTenantResponse)
	err := c.cc.Invoke(ctx, NodeAgent_UpdateTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) SuspendTenant(ctx context.Context, in *SuspendTenantRequest, opts ...grpc.CallOption) (*SuspendTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuspendTenantResponse)
	err := c.cc.Invoke(ctx, NodeAgent_SuspendTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) UnsuspendTenant(ctx context.Context, in *UnsuspendTenantRequest, opts ...grpc.CallOption) (*UnsuspendTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnsuspendTenantResponse)
	err := c.cc.Invoke(ctx, NodeAgent_UnsuspendTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) DeleteTenant(ctx context.Context, in *DeleteTenantRequest, opts ...grpc.CallOption) (*DeleteTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTenantResponse)
	err := c.cc.Invoke(ctx, NodeAgent_DeleteTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) CreateWebroot(ctx context.Context, in *CreateWebrootRequest, opts ...grpc.CallOption) (*CreateWebrootResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWebrootResponse)
	err := c.cc.Invoke(ctx, NodeAgent_CreateWebroot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) UpdateWebroot(ctx context.Context, in *UpdateWebrootRequest, opts ...grpc.CallOption) (*UpdateWebrootResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateWebrootResponse)
	err := c.cc.Invoke(ctx, NodeAgent_UpdateWebroot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) DeleteWebroot(ctx context.Context, in *DeleteWebrootRequest, opts ...grpc.CallOption) (*DeleteWebrootResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWebrootResponse)
	err := c.cc.Invoke(ctx, NodeAgent_DeleteWebroot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) ConfigureRuntime(ctx context.Context, in *ConfigureRuntimeRequest, opts ...grpc.CallOption) (*ConfigureRuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureRuntimeResponse)
	err := c.cc.Invoke(ctx, NodeAgent_ConfigureRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) ReloadNginx(ctx context.Context, in *ReloadNginxRequest, opts ...grpc.CallOption) (*ReloadNginxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadNginxResponse)
	err := c.cc.Invoke(ctx, NodeAgent_ReloadNginx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) CreateDatabase(ctx context.Context, in *CreateDatabaseRequest, opts ...grpc.CallOption) (*CreateDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDatabaseResponse)
	err := c.cc.Invoke(ctx, NodeAgent_CreateDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) DeleteDatabase(ctx context.Context, in *DeleteDatabaseRequest, opts ...grpc.CallOption) (*DeleteDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDatabaseResponse)
	err := c.cc.Invoke(ctx, NodeAgent_DeleteDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) CreateDatabaseUser(ctx context.Context, in *CreateDatabaseUserRequest, opts ...grpc.CallOption) (*CreateDatabaseUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDatabaseUserResponse)
	err := c.cc.Invoke(ctx, NodeAgent_CreateDatabaseUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) UpdateDatabaseUser(ctx context.Context, in *UpdateDatabaseUserRequest, opts ...grpc.CallOption) (*UpdateDatabaseUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDatabaseUserResponse)
	err := c.cc.Invoke(ctx, NodeAgent_UpdateDatabaseUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) DeleteDatabaseUser(ctx context.Context, in *DeleteDatabaseUserRequest, opts ...grpc.CallOption) (*DeleteDatabaseUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDatabaseUserResponse)
	err := c.cc.Invoke(ctx, NodeAgent_DeleteDatabaseUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) CreateValkeyInstance(ctx context.Context, in *CreateValkeyInstanceRequest, opts ...grpc.CallOption) (*CreateValkeyInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateValkeyInstanceResponse)
	err := c.cc.Invoke(ctx, NodeAgent_CreateValkeyInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) DeleteValkeyInstance(ctx context.Context, in *DeleteValkeyInstanceRequest, opts ...grpc.CallOption) (*DeleteValkeyInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteValkeyInstanceResponse)
	err := c.cc.Invoke(ctx, NodeAgent_DeleteValkeyInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) CreateValkeyUser(ctx context.Context, in *CreateValkeyUserRequest, opts ...grpc.CallOption) (*CreateValkeyUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateValkeyUserResponse)
	err := c.cc.Invoke(ctx, NodeAgent_CreateValkeyUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) UpdateValkeyUser(ctx context.Context, in *UpdateValkeyUserRequest, opts ...grpc.CallOption) (*UpdateValkeyUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateValkeyUserResponse)
	err := c.cc.Invoke(ctx, NodeAgent_UpdateValkeyUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) DeleteValkeyUser(ctx context.Context, in *DeleteValkeyUserRequest, opts ...grpc.CallOption) (*DeleteValkeyUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteValkeyUserResponse)
	err := c.cc.Invoke(ctx, NodeAgent_DeleteValkeyUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) InstallCertificate(ctx context.Context, in *InstallCertificateRequest, opts ...grpc.CallOption) (*InstallCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallCertificateResponse)
	err := c.cc.Invoke(ctx, NodeAgent_InstallCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, NodeAgent_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeAgentServer is the server API for NodeAgent service.
// All implementations must embed UnimplementedNodeAgentServer
// for forward compatibility.
type NodeAgentServer interface {
	// Tenant management
	CreateTenant(context.Context, *CreateTenantRequest) (*CreateTenantResponse, error)
	UpdateTenant(context.Context, *UpdateTenantRequest) (*UpdateTenantResponse, error)
	SuspendTenant(context.Context, *SuspendTenantRequest) (*SuspendTenantResponse, error)
	UnsuspendTenant(context.Context, *UnsuspendTenantRequest) (*UnsuspendTenantResponse, error)
	DeleteTenant(context.Context, *DeleteTenantRequest) (*DeleteTenantResponse, error)
	// Webroot management
	CreateWebroot(context.Context, *CreateWebrootRequest) (*CreateWebrootResponse, error)
	UpdateWebroot(context.Context, *UpdateWebrootRequest) (*UpdateWebrootResponse, error)
	DeleteWebroot(context.Context, *DeleteWebrootRequest) (*DeleteWebrootResponse, error)
	// Runtime management
	ConfigureRuntime(context.Context, *ConfigureRuntimeRequest) (*ConfigureRuntimeResponse, error)
	ReloadNginx(context.Context, *ReloadNginxRequest) (*ReloadNginxResponse, error)
	// Database management
	CreateDatabase(context.Context, *CreateDatabaseRequest) (*CreateDatabaseResponse, error)
	DeleteDatabase(context.Context, *DeleteDatabaseRequest) (*DeleteDatabaseResponse, error)
	CreateDatabaseUser(context.Context, *CreateDatabaseUserRequest) (*CreateDatabaseUserResponse, error)
	UpdateDatabaseUser(context.Context, *UpdateDatabaseUserRequest) (*UpdateDatabaseUserResponse, error)
	DeleteDatabaseUser(context.Context, *DeleteDatabaseUserRequest) (*DeleteDatabaseUserResponse, error)
	// Valkey management
	CreateValkeyInstance(context.Context, *CreateValkeyInstanceRequest) (*CreateValkeyInstanceResponse, error)
	DeleteValkeyInstance(context.Context, *DeleteValkeyInstanceRequest) (*DeleteValkeyInstanceResponse, error)
	CreateValkeyUser(context.Context, *CreateValkeyUserRequest) (*CreateValkeyUserResponse, error)
	UpdateValkeyUser(context.Context, *UpdateValkeyUserRequest) (*UpdateValkeyUserResponse, error)
	DeleteValkeyUser(context.Context, *DeleteValkeyUserRequest) (*DeleteValkeyUserResponse, error)
	// SSL
	InstallCertificate(context.Context, *InstallCertificateRequest) (*InstallCertificateResponse, error)
	// Health
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedNodeAgentServer()
}

// UnimplementedNodeAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeAgentServer struct{}

func (UnimplementedNodeAgentServer) CreateTenant(context.Context, *CreateTenantRequest) (*CreateTenantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTenant not implemented")
}
func (UnimplementedNodeAgentServer) UpdateTenant(context.Context, *UpdateTenantRequest) (*UpdateTenantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTenant not implemented")
}
func (UnimplementedNodeAgentServer) SuspendTenant(context.Context, *SuspendTenantRequest) (*SuspendTenantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SuspendTenant not implemented")
}
func (UnimplementedNodeAgentServer) UnsuspendTenant(context.Context, *UnsuspendTenantRequest) (*UnsuspendTenantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnsuspendTenant not implemented")
}
func (UnimplementedNodeAgentServer) DeleteTenant(context.Context, *DeleteTenantRequest) (*DeleteTenantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTenant not implemented")
}
func (UnimplementedNodeAgentServer) CreateWebroot(context.Context, *CreateWebrootRequest) (*CreateWebrootResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWebroot not implemented")
}
func (UnimplementedNodeAgentServer) UpdateWebroot(context.Context, *UpdateWebrootRequest) (*UpdateWebrootResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWebroot not implemented")
}
func (UnimplementedNodeAgentServer) DeleteWebroot(context.Context, *DeleteWebrootRequest) (*DeleteWebrootResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWebroot not implemented")
}
func (UnimplementedNodeAgentServer) ConfigureRuntime(context.Context, *ConfigureRuntimeRequest) (*ConfigureRuntimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureRuntime not implemented")
}
func (UnimplementedNodeAgentServer) ReloadNginx(context.Context, *ReloadNginxRequest) (*ReloadNginxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReloadNginx not implemented")
}
func (UnimplementedNodeAgentServer) CreateDatabase(context.Context, *CreateDatabaseRequest) (*CreateDatabaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDatabase not implemented")
}
func (UnimplementedNodeAgentServer) DeleteDatabase(context.Context, *DeleteDatabaseRequest) (*DeleteDatabaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDatabase not implemented")
}
func (UnimplementedNodeAgentServer) CreateDatabaseUser(context.Context, *CreateDatabaseUserRequest) (*CreateDatabaseUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDatabaseUser not implemented")
}
func (UnimplementedNodeAgentServer) UpdateDatabaseUser(context.Context, *UpdateDatabaseUserRequest) (*UpdateDatabaseUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDatabaseUser not implemented")
}
func (UnimplementedNodeAgentServer) DeleteDatabaseUser(context.Context, *DeleteDatabaseUserRequest) (*DeleteDatabaseUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDatabaseUser not implemented")
}
func (UnimplementedNodeAgentServer) CreateValkeyInstance(context.Context, *CreateValkeyInstanceRequest) (*CreateValkeyInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateValkeyInstance not implemented")
}
func (UnimplementedNodeAgentServer) DeleteValkeyInstance(context.Context, *DeleteValkeyInstanceRequest) (*DeleteValkeyInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteValkeyInstance not implemented")
}
func (UnimplementedNodeAgentServer) CreateValkeyUser(context.Context, *CreateValkeyUserRequest) (*CreateValkeyUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateValkeyUser not implemented")
}
func (UnimplementedNodeAgentServer) UpdateValkeyUser(context.Context, *UpdateValkeyUserRequest) (*UpdateValkeyUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateValkeyUser not implemented")
}
func (UnimplementedNodeAgentServer) DeleteValkeyUser(context.Context, *DeleteValkeyUserRequest) (*DeleteValkeyUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteValkeyUser not implemented")
}
func (UnimplementedNodeAgentServer) InstallCertificate(context.Context, *InstallCertificateRequest) (*InstallCertificateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InstallCertificate not implemented")
}
func (UnimplementedNodeAgentServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedNodeAgentServer) mustEmbedUnimplementedNodeAgentServer() {}
func (UnimplementedNodeAgentServer) testEmbeddedByValue()                   {}

// UnsafeNodeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeAgentServer will
// result in compilation errors.
type UnsafeNodeAgentServer interface {
	mustEmbedUnimplementedNodeAgentServer()
}

func RegisterNodeAgentServer(s grpc.ServiceRegistrar, srv NodeAgentServer) {
	// If the following call panics, it indicates UnimplementedNodeAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeAgent_ServiceDesc, srv)
}

func _NodeAgent_CreateTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).CreateTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_CreateTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).CreateTenant(ctx, req.(*CreateTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_UpdateTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).UpdateTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_UpdateTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).UpdateTenant(ctx, req.(*UpdateTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_SuspendTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).SuspendTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_SuspendTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).SuspendTenant(ctx, req.(*SuspendTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_UnsuspendTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsuspendTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).UnsuspendTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_UnsuspendTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).UnsuspendTenant(ctx, req.(*UnsuspendTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_DeleteTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).DeleteTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_DeleteTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).DeleteTenant(ctx, req.(*DeleteTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_CreateWebroot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWebrootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).CreateWebroot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_CreateWebroot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).CreateWebroot(ctx, req.(*CreateWebrootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_UpdateWebroot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWebrootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).UpdateWebroot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_UpdateWebroot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).UpdateWebroot(ctx, req.(*UpdateWebrootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_DeleteWebroot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWebrootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).DeleteWebroot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_DeleteWebroot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).DeleteWebroot(ctx, req.(*DeleteWebrootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_ConfigureRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).ConfigureRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_ConfigureRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).ConfigureRuntime(ctx, req.(*ConfigureRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_ReloadNginx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadNginxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).ReloadNginx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_ReloadNginx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).ReloadNginx(ctx, req.(*ReloadNginxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_CreateDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).CreateDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_CreateDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).CreateDatabase(ctx, req.(*CreateDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_DeleteDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).DeleteDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_DeleteDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).DeleteDatabase(ctx, req.(*DeleteDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_CreateDatabaseUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDatabaseUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).CreateDatabaseUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_CreateDatabaseUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).CreateDatabaseUser(ctx, req.(*CreateDatabaseUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_UpdateDatabaseUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDatabaseUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).UpdateDatabaseUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_UpdateDatabaseUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).UpdateDatabaseUser(ctx, req.(*UpdateDatabaseUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_DeleteDatabaseUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDatabaseUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).DeleteDatabaseUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_DeleteDatabaseUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).DeleteDatabaseUser(ctx, req.(*DeleteDatabaseUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_CreateValkeyInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateValkeyInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).CreateValkeyInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_CreateValkeyInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).CreateValkeyInstance(ctx, req.(*CreateValkeyInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_DeleteValkeyInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteValkeyInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).DeleteValkeyInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_DeleteValkeyInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).DeleteValkeyInstance(ctx, req.(*DeleteValkeyInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_CreateValkeyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateValkeyUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).CreateValkeyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_CreateValkeyUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).CreateValkeyUser(ctx, req.(*CreateValkeyUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_UpdateValkeyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateValkeyUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).UpdateValkeyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_UpdateValkeyUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).UpdateValkeyUser(ctx, req.(*UpdateValkeyUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_DeleteValkeyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteValkeyUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).DeleteValkeyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_DeleteValkeyUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).DeleteValkeyUser(ctx, req.(*DeleteValkeyUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_InstallCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).InstallCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_InstallCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).InstallCertificate(ctx, req.(*InstallCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeAgent_ServiceDesc is the grpc.ServiceDesc for NodeAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.v1.NodeAgent",
	HandlerType: (*NodeAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTenant",
			Handler:    _NodeAgent_CreateTenant_Handler,
		},
		{
			MethodName: "UpdateTenant",
			Handler:    _NodeAgent_UpdateTenant_Handler,
		},
		{
			MethodName: "SuspendTenant",
			Handler:    _NodeAgent_SuspendTenant_Handler,
		},
		{
			MethodName: "UnsuspendTenant",
			Handler:    _NodeAgent_UnsuspendTenant_Handler,
		},
		{
			MethodName: "DeleteTenant",
			Handler:    _NodeAgent_DeleteTenant_Handler,
		},
		{
			MethodName: "CreateWebroot",
			Handler:    _NodeAgent_CreateWebroot_Handler,
		},
		{
			MethodName: "UpdateWebroot",
			Handler:    _NodeAgent_UpdateWebroot_Handler,
		},
		{
			MethodName: "DeleteWebroot",
			Handler:    _NodeAgent_DeleteWebroot_Handler,
		},
		{
			MethodName: "ConfigureRuntime",
			Handler:    _NodeAgent_ConfigureRuntime_Handler,
		},
		{
			MethodName: "ReloadNginx",
			Handler:    _NodeAgent_ReloadNginx_Handler,
		},
		{
			MethodName: "CreateDatabase",
			Handler:    _NodeAgent_CreateDatabase_Handler,
		},
		{
			MethodName: "DeleteDatabase",
			Handler:    _NodeAgent_DeleteDatabase_Handler,
		},
		{
			MethodName: "CreateDatabaseUser",
			Handler:    _NodeAgent_CreateDatabaseUser_Handler,
		},
		{
			MethodName: "UpdateDatabaseUser",
			Handler:    _NodeAgent_UpdateDatabaseUser_Handler,
		},
		{
			MethodName: "DeleteDatabaseUser",
			Handler:    _NodeAgent_DeleteDatabaseUser_Handler,
		},
		{
			MethodName: "CreateValkeyInstance",
			Handler:    _NodeAgent_CreateValkeyInstance_Handler,
		},
		{
			MethodName: "DeleteValkeyInstance",
			Handler:    _NodeAgent_DeleteValkeyInstance_Handler,
		},
		{
			MethodName: "CreateValkeyUser",
			Handler:    _NodeAgent_CreateValkeyUser_Handler,
		},
		{
			MethodName: "UpdateValkeyUser",
			Handler:    _NodeAgent_UpdateValkeyUser_Handler,
		},
		{
			MethodName: "DeleteValkeyUser",
			Handler:    _NodeAgent_DeleteValkeyUser_Handler,
		},
		{
			MethodName: "InstallCertificate",
			Handler:    _NodeAgent_InstallCertificate_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _NodeAgent_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent/v1/agent.proto",
}
