// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tenant messages
type CreateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *TenantInfo            `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantRequest) Reset() {
	*x = CreateTenantRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantRequest) ProtoMessage() {}

func (x *CreateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantRequest.ProtoReflect.Descriptor instead.
func (*CreateTenantRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTenantRequest) GetTenant() *TenantInfo {
	if x != nil {
		return x.Tenant
	}
	return nil
}

type CreateTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantResponse) Reset() {
	*x = CreateTenantResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantResponse) ProtoMessage() {}

func (x *CreateTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantResponse.ProtoReflect.Descriptor instead.
func (*CreateTenantResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

type UpdateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *TenantInfo            `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTenantRequest) Reset() {
	*x = UpdateTenantRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantRequest) ProtoMessage() {}

func (x *UpdateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantRequest.ProtoReflect.Descriptor instead.
func (*UpdateTenantRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTenantRequest) GetTenant() *TenantInfo {
	if x != nil {
		return x.Tenant
	}
	return nil
}

type UpdateTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTenantResponse) Reset() {
	*x = UpdateTenantResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantResponse) ProtoMessage() {}

func (x *UpdateTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantResponse.ProtoReflect.Descriptor instead.
func (*UpdateTenantResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

type SuspendTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantName    string                 `protobuf:"bytes,1,opt,name=tenant_name,json=tenantName,proto3" json:"tenant_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendTenantRequest) Reset() {
	*x = SuspendTenantRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendTenantRequest) ProtoMessage() {}

func (x *SuspendTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendTenantRequest.ProtoReflect.Descriptor instead.
func (*SuspendTenantRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *SuspendTenantRequest) GetTenantName() string {
	if x != nil {
		return x.TenantName
	}
	return ""
}

type SuspendTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendTenantResponse) Reset() {
	*x = SuspendTenantResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendTenantResponse) ProtoMessage() {}

func (x *SuspendTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendTenantResponse.ProtoReflect.Descriptor instead.
func (*SuspendTenantResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

type UnsuspendTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantName    string                 `protobuf:"bytes,1,opt,name=tenant_name,json=tenantName,proto3" json:"tenant_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsuspendTenantRequest) Reset() {
	*x = UnsuspendTenantRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsuspendTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsuspendTenantRequest) ProtoMessage() {}

func (x *UnsuspendTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsuspendTenantRequest.ProtoReflect.Descriptor instead.
func (*UnsuspendTenantRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *UnsuspendTenantRequest) GetTenantName() string {
	if x != nil {
		return x.TenantName
	}
	return ""
}

type UnsuspendTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsuspendTenantResponse) Reset() {
	*x = UnsuspendTenantResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsuspendTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsuspendTenantResponse) ProtoMessage() {}

func (x *UnsuspendTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsuspendTenantResponse.ProtoReflect.Descriptor instead.
func (*UnsuspendTenantResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

type DeleteTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantName    string                 `protobuf:"bytes,1,opt,name=tenant_name,json=tenantName,proto3" json:"tenant_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTenantRequest) Reset() {
	*x = DeleteTenantRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantRequest) ProtoMessage() {}

func (x *DeleteTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantRequest.ProtoReflect.Descriptor instead.
func (*DeleteTenantRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTenantRequest) GetTenantName() string {
	if x != nil {
		return x.TenantName
	}
	return ""
}

type DeleteTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTenantResponse) Reset() {
	*x = DeleteTenantResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantResponse) ProtoMessage() {}

func (x *DeleteTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantResponse.ProtoReflect.Descriptor instead.
func (*DeleteTenantResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

// Webroot messages
type CreateWebrootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Webroot       *WebrootInfo           `protobuf:"bytes,1,opt,name=webroot,proto3" json:"webroot,omitempty"`
	Fqdns         []*FQDNInfo            `protobuf:"bytes,2,rep,name=fqdns,proto3" json:"fqdns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWebrootRequest) Reset() {
	*x = CreateWebrootRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWebrootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWebrootRequest) ProtoMessage() {}

func (x *CreateWebrootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWebrootRequest.ProtoReflect.Descriptor instead.
func (*CreateWebrootRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *CreateWebrootRequest) GetWebroot() *WebrootInfo {
	if x != nil {
		return x.Webroot
	}
	return nil
}

func (x *CreateWebrootRequest) GetFqdns() []*FQDNInfo {
	if x != nil {
		return x.Fqdns
	}
	return nil
}

type CreateWebrootResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWebrootResponse) Reset() {
	*x = CreateWebrootResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWebrootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWebrootResponse) ProtoMessage() {}

func (x *CreateWebrootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWebrootResponse.ProtoReflect.Descriptor instead.
func (*CreateWebrootResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

type UpdateWebrootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Webroot       *WebrootInfo           `protobuf:"bytes,1,opt,name=webroot,proto3" json:"webroot,omitempty"`
	Fqdns         []*FQDNInfo            `protobuf:"bytes,2,rep,name=fqdns,proto3" json:"fqdns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWebrootRequest) Reset() {
	*x = UpdateWebrootRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWebrootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWebrootRequest) ProtoMessage() {}

func (x *UpdateWebrootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWebrootRequest.ProtoReflect.Descriptor instead.
func (*UpdateWebrootRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateWebrootRequest) GetWebroot() *WebrootInfo {
	if x != nil {
		return x.Webroot
	}
	return nil
}

func (x *UpdateWebrootRequest) GetFqdns() []*FQDNInfo {
	if x != nil {
		return x.Fqdns
	}
	return nil
}

type UpdateWebrootResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWebrootResponse) Reset() {
	*x = UpdateWebrootResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWebrootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWebrootResponse) ProtoMessage() {}

func (x *UpdateWebrootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWebrootResponse.ProtoReflect.Descriptor instead.
func (*UpdateWebrootResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{13}
}

type DeleteWebrootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantName    string                 `protobuf:"bytes,1,opt,name=tenant_name,json=tenantName,proto3" json:"tenant_name,omitempty"`
	WebrootName   string                 `protobuf:"bytes,2,opt,name=webroot_name,json=webrootName,proto3" json:"webroot_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWebrootRequest) Reset() {
	*x = DeleteWebrootRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWebrootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWebrootRequest) ProtoMessage() {}

func (x *DeleteWebrootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWebrootRequest.ProtoReflect.Descriptor instead.
func (*DeleteWebrootRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteWebrootRequest) GetTenantName() string {
	if x != nil {
		return x.TenantName
	}
	return ""
}

func (x *DeleteWebrootRequest) GetWebrootName() string {
	if x != nil {
		return x.WebrootName
	}
	return ""
}

type DeleteWebrootResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWebrootResponse) Reset() {
	*x = DeleteWebrootResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWebrootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWebrootResponse) ProtoMessage() {}

func (x *DeleteWebrootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWebrootResponse.ProtoReflect.Descriptor instead.
func (*DeleteWebrootResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{15}
}

// Runtime messages
type ConfigureRuntimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Webroot       *WebrootInfo           `protobuf:"bytes,1,opt,name=webroot,proto3" json:"webroot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRuntimeRequest) Reset() {
	*x = ConfigureRuntimeRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRuntimeRequest) ProtoMessage() {}

func (x *ConfigureRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRuntimeRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *ConfigureRuntimeRequest) GetWebroot() *WebrootInfo {
	if x != nil {
		return x.Webroot
	}
	return nil
}

type ConfigureRuntimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRuntimeResponse) Reset() {
	*x = ConfigureRuntimeResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRuntimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRuntimeResponse) ProtoMessage() {}

func (x *ConfigureRuntimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRuntimeResponse.ProtoReflect.Descriptor instead.
func (*ConfigureRuntimeResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{17}
}

type ReloadNginxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadNginxRequest) Reset() {
	*x = ReloadNginxRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadNginxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadNginxRequest) ProtoMessage() {}

func (x *ReloadNginxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadNginxRequest.ProtoReflect.Descriptor instead.
func (*ReloadNginxRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{18}
}

type ReloadNginxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadNginxResponse) Reset() {
	*x = ReloadNginxResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadNginxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadNginxResponse) ProtoMessage() {}

func (x *ReloadNginxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadNginxResponse.ProtoReflect.Descriptor instead.
func (*ReloadNginxResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{19}
}

// Database messages
type CreateDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *DatabaseInfo          `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDatabaseRequest) Reset() {
	*x = CreateDatabaseRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDatabaseRequest) ProtoMessage() {}

func (x *CreateDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDatabaseRequest.ProtoReflect.Descriptor instead.
func (*CreateDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{20}
}

func (x *CreateDatabaseRequest) GetDatabase() *DatabaseInfo {
	if x != nil {
		return x.Database
	}
	return nil
}

type CreateDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDatabaseResponse) Reset() {
	*x = CreateDatabaseResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDatabaseResponse) ProtoMessage() {}

func (x *CreateDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDatabaseResponse.ProtoReflect.Descriptor instead.
func (*CreateDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{21}
}

type DeleteDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseName  string                 `protobuf:"bytes,1,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDatabaseRequest) Reset() {
	*x = DeleteDatabaseRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDatabaseRequest) ProtoMessage() {}

func (x *DeleteDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDatabaseRequest.ProtoReflect.Descriptor instead.
func (*DeleteDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteDatabaseRequest) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

type DeleteDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDatabaseResponse) Reset() {
	*x = DeleteDatabaseResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDatabaseResponse) ProtoMessage() {}

func (x *DeleteDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDatabaseResponse.ProtoReflect.Descriptor instead.
func (*DeleteDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{23}
}

type CreateDatabaseUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *DatabaseUserInfo      `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDatabaseUserRequest) Reset() {
	*x = CreateDatabaseUserRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDatabaseUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDatabaseUserRequest) ProtoMessage() {}

func (x *CreateDatabaseUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDatabaseUserRequest.ProtoReflect.Descriptor instead.
func (*CreateDatabaseUserRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{24}
}

func (x *CreateDatabaseUserRequest) GetUser() *DatabaseUserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type CreateDatabaseUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDatabaseUserResponse) Reset() {
	*x = CreateDatabaseUserResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDatabaseUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDatabaseUserResponse) ProtoMessage() {}

func (x *CreateDatabaseUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDatabaseUserResponse.ProtoReflect.Descriptor instead.
func (*CreateDatabaseUserResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{25}
}

type UpdateDatabaseUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *DatabaseUserInfo      `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDatabaseUserRequest) Reset() {
	*x = UpdateDatabaseUserRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDatabaseUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDatabaseUserRequest) ProtoMessage() {}

func (x *UpdateDatabaseUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDatabaseUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateDatabaseUserRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateDatabaseUserRequest) GetUser() *DatabaseUserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateDatabaseUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDatabaseUserResponse) Reset() {
	*x = UpdateDatabaseUserResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDatabaseUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDatabaseUserResponse) ProtoMessage() {}

func (x *UpdateDatabaseUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDatabaseUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateDatabaseUserResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{27}
}

type DeleteDatabaseUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseName  string                 `protobuf:"bytes,1,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDatabaseUserRequest) Reset() {
	*x = DeleteDatabaseUserRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDatabaseUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDatabaseUserRequest) ProtoMessage() {}

func (x *DeleteDatabaseUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDatabaseUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteDatabaseUserRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteDatabaseUserRequest) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *DeleteDatabaseUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type DeleteDatabaseUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDatabaseUserResponse) Reset() {
	*x = DeleteDatabaseUserResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDatabaseUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDatabaseUserResponse) ProtoMessage() {}

func (x *DeleteDatabaseUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDatabaseUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteDatabaseUserResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{29}
}

// Valkey messages
type CreateValkeyInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *ValkeyInstanceInfo    `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateValkeyInstanceRequest) Reset() {
	*x = CreateValkeyInstanceRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateValkeyInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateValkeyInstanceRequest) ProtoMessage() {}

func (x *CreateValkeyInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateValkeyInstanceRequest.ProtoReflect.Descriptor instead.
func (*CreateValkeyInstanceRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{30}
}

func (x *CreateValkeyInstanceRequest) GetInstance() *ValkeyInstanceInfo {
	if x != nil {
		return x.Instance
	}
	return nil
}

type CreateValkeyInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateValkeyInstanceResponse) Reset() {
	*x = CreateValkeyInstanceResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateValkeyInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateValkeyInstanceResponse) ProtoMessage() {}

func (x *CreateValkeyInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateValkeyInstanceResponse.ProtoReflect.Descriptor instead.
func (*CreateValkeyInstanceResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{31}
}

type DeleteValkeyInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceName  string                 `protobuf:"bytes,1,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteValkeyInstanceRequest) Reset() {
	*x = DeleteValkeyInstanceRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteValkeyInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteValkeyInstanceRequest) ProtoMessage() {}

func (x *DeleteValkeyInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteValkeyInstanceRequest.ProtoReflect.Descriptor instead.
func (*DeleteValkeyInstanceRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{32}
}

func (x *DeleteValkeyInstanceRequest) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *DeleteValkeyInstanceRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type DeleteValkeyInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteValkeyInstanceResponse) Reset() {
	*x = DeleteValkeyInstanceResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteValkeyInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteValkeyInstanceResponse) ProtoMessage() {}

func (x *DeleteValkeyInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteValkeyInstanceResponse.ProtoReflect.Descriptor instead.
func (*DeleteValkeyInstanceResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{33}
}

type CreateValkeyUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *ValkeyUserInfo        `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateValkeyUserRequest) Reset() {
	*x = CreateValkeyUserRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateValkeyUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateValkeyUserRequest) ProtoMessage() {}

func (x *CreateValkeyUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateValkeyUserRequest.ProtoReflect.Descriptor instead.
func (*CreateValkeyUserRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{34}
}

func (x *CreateValkeyUserRequest) GetUser() *ValkeyUserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type CreateValkeyUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateValkeyUserResponse) Reset() {
	*x = CreateValkeyUserResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateValkeyUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateValkeyUserResponse) ProtoMessage() {}

func (x *CreateValkeyUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateValkeyUserResponse.ProtoReflect.Descriptor instead.
func (*CreateValkeyUserResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{35}
}

type UpdateValkeyUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *ValkeyUserInfo        `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateValkeyUserRequest) Reset() {
	*x = UpdateValkeyUserRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateValkeyUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateValkeyUserRequest) ProtoMessage() {}

func (x *UpdateValkeyUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateValkeyUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateValkeyUserRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{36}
}

func (x *UpdateValkeyUserRequest) GetUser() *ValkeyUserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateValkeyUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateValkeyUserResponse) Reset() {
	*x = UpdateValkeyUserResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateValkeyUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateValkeyUserResponse) ProtoMessage() {}

func (x *UpdateValkeyUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateValkeyUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateValkeyUserResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{37}
}

type DeleteValkeyUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceName  string                 `protobuf:"bytes,1,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteValkeyUserRequest) Reset() {
	*x = DeleteValkeyUserRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteValkeyUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteValkeyUserRequest) ProtoMessage() {}

func (x *DeleteValkeyUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteValkeyUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteValkeyUserRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{38}
}

func (x *DeleteValkeyUserRequest) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *DeleteValkeyUserRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DeleteValkeyUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type DeleteValkeyUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteValkeyUserResponse) Reset() {
	*x = DeleteValkeyUserResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteValkeyUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteValkeyUserResponse) ProtoMessage() {}

func (x *DeleteValkeyUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteValkeyUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteValkeyUserResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{39}
}

// SSL messages
type InstallCertificateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   *CertificateInfo       `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallCertificateRequest) Reset() {
	*x = InstallCertificateRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallCertificateRequest) ProtoMessage() {}

func (x *InstallCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallCertificateRequest.ProtoReflect.Descriptor instead.
func (*InstallCertificateRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{40}
}

func (x *InstallCertificateRequest) GetCertificate() *CertificateInfo {
	if x != nil {
		return x.Certificate
	}
	return nil
}

type InstallCertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallCertificateResponse) Reset() {
	*x = InstallCertificateResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallCertificateResponse) ProtoMessage() {}

func (x *InstallCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallCertificateResponse.ProtoReflect.Descriptor instead.
func (*InstallCertificateResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{41}
}

// Health messages
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{42}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{43}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_agent_v1_agent_proto protoreflect.FileDescriptor

const file_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14agent/v1/agent.proto\x12\bagent.v1\x1a\x14agent/v1/types.proto\"C\n" +
	"\x13CreateTenantRequest\x12,\n" +
	"\x06tenant\x18\x01 \x01(\v2\x14.agent.v1.TenantInfoR\x06tenant\"\x16\n" +
	"\x14CreateTenantResponse\"C\n" +
	"\x13UpdateTenantRequest\x12,\n" +
	"\x06tenant\x18\x01 \x01(\v2\x14.agent.v1.TenantInfoR\x06tenant\"\x16\n" +
	"\x14UpdateTenantResponse\"7\n" +
	"\x14SuspendTenantRequest\x12\x1f\n" +
	"\vtenant_name\x18\x01 \x01(\tR\n" +
	"tenantName\"\x17\n" +
	"\x15SuspendTenantResponse\"9\n" +
	"\x16UnsuspendTenantRequest\x12\x1f\n" +
	"\vtenant_name\x18\x01 \x01(\tR\n" +
	"tenantName\"\x19\n" +
	"\x17UnsuspendTenantResponse\"6\n" +
	"\x13DeleteTenantRequest\x12\x1f\n" +
	"\vtenant_name\x18\x01 \x01(\tR\n" +
	"tenantName\"\x16\n" +
	"\x14DeleteTenantResponse\"q\n" +
	"\x14CreateWebrootRequest\x12/\n" +
	"\awebroot\x18\x01 \x01(\v2\x15.agent.v1.WebrootInfoR\awebroot\x12(\n" +
	"\x05fqdns\x18\x02 \x03(\v2\x12.agent.v1.FQDNInfoR\x05fqdns\"\x17\n" +
	"\x15CreateWebrootResponse\"q\n" +
	"\x14UpdateWebrootRequest\x12/\n" +
	"\awebroot\x18\x01 \x01(\v2\x15.agent.v1.WebrootInfoR\awebroot\x12(\n" +
	"\x05fqdns\x18\x02 \x03(\v2\x12.agent.v1.FQDNInfoR\x05fqdns\"\x17\n" +
	"\x15UpdateWebrootResponse\"Z\n" +
	"\x14DeleteWebrootRequest\x12\x1f\n" +
	"\vtenant_name\x18\x01 \x01(\tR\n" +
	"tenantName\x12!\n" +
	"\fwebroot_name\x18\x02 \x01(\tR\vwebrootName\"\x17\n" +
	"\x15DeleteWebrootResponse\"J\n" +
	"\x17ConfigureRuntimeRequest\x12/\n" +
	"\awebroot\x18\x01 \x01(\v2\x15.agent.v1.WebrootInfoR\awebroot\"\x1a\n" +
	"\x18ConfigureRuntimeResponse\"\x14\n" +
	"\x12ReloadNginxRequest\"\x15\n" +
	"\x13ReloadNginxResponse\"K\n" +
	"\x15CreateDatabaseRequest\x122\n" +
	"\bdatabase\x18\x01 \x01(\v2\x16.agent.v1.DatabaseInfoR\bdatabase\"\x18\n" +
	"\x16CreateDatabaseResponse\"<\n" +
	"\x15DeleteDatabaseRequest\x12#\n" +
	"\rdatabase_name\x18\x01 \x01(\tR\fdatabaseName\"\x18\n" +
	"\x16DeleteDatabaseResponse\"K\n" +
	"\x19CreateDatabaseUserRequest\x12.\n" +
	"\x04user\x18\x01 \x01(\v2\x1a.agent.v1.DatabaseUserInfoR\x04user\"\x1c\n" +
	"\x1aCreateDatabaseUserResponse\"K\n" +
	"\x19UpdateDatabaseUserRequest\x12.\n" +
	"\x04user\x18\x01 \x01(\v2\x1a.agent.v1.DatabaseUserInfoR\x04user\"\x1c\n" +
	"\x1aUpdateDatabaseUserResponse\"\\\n" +
	"\x19DeleteDatabaseUserRequest\x12#\n" +
	"\rdatabase_name\x18\x01 \x01(\tR\fdatabaseName\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"\x1c\n" +
	"\x1aDeleteDatabaseUserResponse\"W\n" +
	"\x1bCreateValkeyInstanceRequest\x128\n" +
	"\binstance\x18\x01 \x01(\v2\x1c.agent.v1.ValkeyInstanceInfoR\binstance\"\x1e\n" +
	"\x1cCreateValkeyInstanceResponse\"V\n" +
	"\x1bDeleteValkeyInstanceRequest\x12#\n" +
	"\rinstance_name\x18\x01 \x01(\tR\finstanceName\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"\x1e\n" +
	"\x1cDeleteValkeyInstanceResponse\"G\n" +
	"\x17CreateValkeyUserRequest\x12,\n" +
	"\x04user\x18\x01 \x01(\v2\x18.agent.v1.ValkeyUserInfoR\x04user\"\x1a\n" +
	"\x18CreateValkeyUserResponse\"G\n" +
	"\x17UpdateValkeyUserRequest\x12,\n" +
	"\x04user\x18\x01 \x01(\v2\x18.agent.v1.ValkeyUserInfoR\x04user\"\x1a\n" +
	"\x18UpdateValkeyUserResponse\"n\n" +
	"\x17DeleteValkeyUserRequest\x12#\n" +
	"\rinstance_name\x18\x01 \x01(\tR\finstanceName\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\"\x1a\n" +
	"\x18DeleteValkeyUserResponse\"X\n" +
	"\x19InstallCertificateRequest\x12;\n" +
	"\vcertificate\x18\x01 \x01(\v2\x19.agent.v1.CertificateInfoR\vcertificate\"\x1c\n" +
	"\x1aInstallCertificateResponse\"\x14\n" +
	"\x12HealthCheckRequest\"I\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x98\x0f\n" +
	"\tNodeAgent\x12M\n" +
	"\fCreateTenant\x12\x1d.agent.v1.CreateTenantRequest\x1a\x1e.agent.v1.CreateTenantResponse\x12M\n" +
	"\fUpdateTenant\x12\x1d.agent.v1.UpdateTenantRequest\x1a\x1e.agent.v1.UpdateTenantResponse\x12P\n" +
	"\rSuspendTenant\x12\x1e.agent.v1.SuspendTenantRequest\x1a\x1f.agent.v1.SuspendTenantResponse\x12V\n" +
	"\x0fUnsuspendTenant\x12 .agent.v1.UnsuspendTenantRequest\x1a!.agent.v1.UnsuspendTenantResponse\x12M\n" +
	"\fDeleteTenant\x12\x1d.agent.v1.DeleteTenantRequest\x1a\x1e.agent.v1.DeleteTenantResponse\x12P\n" +
	"\rCreateWebroot\x12\x1e.agent.v1.CreateWebrootRequest\x1a\x1f.agent.v1.CreateWebrootResponse\x12P\n" +
	"\rUpdateWebroot\x12\x1e.agent.v1.UpdateWebrootRequest\x1a\x1f.agent.v1.UpdateWebrootResponse\x12P\n" +
	"\rDeleteWebroot\x12\x1e.agent.v1.DeleteWebrootRequest\x1a\x1f.agent.v1.DeleteWebrootResponse\x12Y\n" +
	"\x10ConfigureRuntime\x12!.agent.v1.ConfigureRuntimeRequest\x1a\".agent.v1.ConfigureRuntimeResponse\x12J\n" +
	"\vReloadNginx\x12\x1c.agent.v1.ReloadNginxRequest\x1a\x1d.agent.v1.ReloadNginxResponse\x12S\n" +
	"\x0eCreateDatabase\x12\x1f.agent.v1.CreateDatabaseRequest\x1a .agent.v1.CreateDatabaseResponse\x12S\n" +
	"\x0eDeleteDatabase\x12\x1f.agent.v1.DeleteDatabaseRequest\x1a .agent.v1.DeleteDatabaseResponse\x12_\n" +
	"\x12CreateDatabaseUser\x12#.agent.v1.CreateDatabaseUserRequest\x1a$.agent.v1.CreateDatabaseUserResponse\x12_\n" +
	"\x12UpdateDatabaseUser\x12#.agent.v1.UpdateDatabaseUserRequest\x1a$.agent.v1.UpdateDatabaseUserResponse\x12_\n" +
	"\x12DeleteDatabaseUser\x12#.agent.v1.DeleteDatabaseUserRequest\x1a$.agent.v1.DeleteDatabaseUserResponse\x12e\n" +
	"\x14CreateValkeyInstance\x12%.agent.v1.CreateValkeyInstanceRequest\x1a&.agent.v1.CreateValkeyInstanceResponse\x12e\n" +
	"\x14DeleteValkeyInstance\x12%.agent.v1.DeleteValkeyInstanceRequest\x1a&.agent.v1.DeleteValkeyInstanceResponse\x12Y\n" +
	"\x10CreateValkeyUser\x12!.agent.v1.CreateValkeyUserRequest\x1a\".agent.v1.CreateValkeyUserResponse\x12Y\n" +
	"\x10UpdateValkeyUser\x12!.agent.v1.UpdateValkeyUserRequest\x1a\".agent.v1.UpdateValkeyUserResponse\x12Y\n" +
	"\x10DeleteValkeyUser\x12!.agent.v1.DeleteValkeyUserRequest\x1a\".agent.v1.DeleteValkeyUserResponse\x12_\n" +
	"\x12InstallCertificate\x12#.agent.v1.InstallCertificateRequest\x1a$.agent.v1.InstallCertificateResponse\x12J\n" +
	"\vHealthCheck\x12\x1c.agent.v1.HealthCheckRequest\x1a\x1d.agent.v1.HealthCheckResponseB1Z/github.com/edvin/hosting/proto/agent/v1;agentv1b\x06proto3"

var (
	file_agent_v1_agent_proto_rawDescOnce sync.Once
	file_agent_v1_agent_proto_rawDescData []byte
)

func file_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)))
	})
	return file_agent_v1_agent_proto_rawDescData
}

var file_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 44)
var file_agent_v1_agent_proto_goTypes = []any{
	(*CreateTenantRequest)(nil),          // 0: agent.v1.CreateTenantRequest
	(*CreateTenantResponse)(nil),         // 1: agent.v1.CreateTenantResponse
	(*UpdateTenantRequest)(nil),          // 2: agent.v1.UpdateTenantRequest
	(*UpdateTenantResponse)(nil),         // 3: agent.v1.UpdateTenantResponse
	(*SuspendTenantRequest)(nil),         // 4: agent.v1.SuspendTenantRequest
	(*SuspendTenantResponse)(nil),        // 5: agent.v1.SuspendTenantResponse
	(*UnsuspendTenantRequest)(nil),       // 6: agent.v1.UnsuspendTenantRequest
	(*UnsuspendTenantResponse)(nil),      // 7: agent.v1.UnsuspendTenantResponse
	(*DeleteTenantRequest)(nil),          // 8: agent.v1.DeleteTenantRequest
	(*DeleteTenantResponse)(nil),         // 9: agent.v1.DeleteTenantResponse
	(*CreateWebrootRequest)(nil),         // 10: agent.v1.CreateWebrootRequest
	(*CreateWebrootResponse)(nil),        // 11: agent.v1.CreateWebrootResponse
	(*UpdateWebrootRequest)(nil),         // 12: agent.v1.UpdateWebrootRequest
	(*UpdateWebrootResponse)(nil),        // 13: agent.v1.UpdateWebrootResponse
	(*DeleteWebrootRequest)(nil),         // 14: agent.v1.DeleteWebrootRequest
	(*DeleteWebrootResponse)(nil),        // 15: agent.v1.DeleteWebrootResponse
	(*ConfigureRuntimeRequest)(nil),      // 16: agent.v1.ConfigureRuntimeRequest
	(*ConfigureRuntimeResponse)(nil),     // 17: agent.v1.ConfigureRuntimeResponse
	(*ReloadNginxRequest)(nil),           // 18: agent.v1.ReloadNginxRequest
	(*ReloadNginxResponse)(nil),          // 19: agent.v1.ReloadNginxResponse
	(*CreateDatabaseRequest)(nil),        // 20: agent.v1.CreateDatabaseRequest
	(*CreateDatabaseResponse)(nil),       // 21: agent.v1.CreateDatabaseResponse
	(*DeleteDatabaseRequest)(nil),        // 22: agent.v1.DeleteDatabaseRequest
	(*DeleteDatabaseResponse)(nil),       // 23: agent.v1.DeleteDatabaseResponse
	(*CreateDatabaseUserRequest)(nil),    // 24: agent.v1.CreateDatabaseUserRequest
	(*CreateDatabaseUserResponse)(nil),   // 25: agent.v1.CreateDatabaseUserResponse
	(*UpdateDatabaseUserRequest)(nil),    // 26: agent.v1.UpdateDatabaseUserRequest
	(*UpdateDatabaseUserResponse)(nil),   // 27: agent.v1.UpdateDatabaseUserResponse
	(*DeleteDatabaseUserRequest)(nil),    // 28: agent.v1.DeleteDatabaseUserRequest
	(*DeleteDatabaseUserResponse)(nil),   // 29: agent.v1.DeleteDatabaseUserResponse
	(*CreateValkeyInstanceRequest)(nil),  // 30: agent.v1.CreateValkeyInstanceRequest
	(*CreateValkeyInstanceResponse)(nil), // 31: agent.v1.CreateValkeyInstanceResponse
	(*DeleteValkeyInstanceRequest)(nil),  // 32: agent.v1.DeleteValkeyInstanceRequest
	(*DeleteValkeyInstanceResponse)(nil), // 33: agent.v1.DeleteValkeyInstanceResponse
	(*CreateValkeyUserRequest)(nil),      // 34: agent.v1.CreateValkeyUserRequest
	(*CreateValkeyUserResponse)(nil),     // 35: agent.v1.CreateValkeyUserResponse
	(*UpdateValkeyUserRequest)(nil),      // 36: agent.v1.UpdateValkeyUserRequest
	(*UpdateValkeyUserResponse)(nil),     // 37: agent.v1.UpdateValkeyUserResponse
	(*DeleteValkeyUserRequest)(nil),      // 38: agent.v1.DeleteValkeyUserRequest
	(*DeleteValkeyUserResponse)(nil),     // 39: agent.v1.DeleteValkeyUserResponse
	(*InstallCertificateRequest)(nil),    // 40: agent.v1.InstallCertificateRequest
	(*InstallCertificateResponse)(nil),   // 41: agent.v1.InstallCertificateResponse
	(*HealthCheckRequest)(nil),           // 42: agent.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),          // 43: agent.v1.HealthCheckResponse
	(*TenantInfo)(nil),                   // 44: agent.v1.TenantInfo
	(*WebrootInfo)(nil),                  // 45: agent.v1.WebrootInfo
	(*FQDNInfo)(nil),                     // 46: agent.v1.FQDNInfo
	(*DatabaseInfo)(nil),                 // 47: agent.v1.DatabaseInfo
	(*DatabaseUserInfo)(nil),             // 48: agent.v1.DatabaseUserInfo
	(*ValkeyInstanceInfo)(nil),           // 49: agent.v1.ValkeyInstanceInfo
	(*ValkeyUserInfo)(nil),               // 50: agent.v1.ValkeyUserInfo
	(*CertificateInfo)(nil),              // 51: agent.v1.CertificateInfo
}
var file_agent_v1_agent_proto_depIdxs = []int32{
	44, // 0: agent.v1.CreateTenantRequest.tenant:type_name -> agent.v1.TenantInfo
	44, // 1: agent.v1.UpdateTenantRequest.tenant:type_name -> agent.v1.TenantInfo
	45, // 2: agent.v1.CreateWebrootRequest.webroot:type_name -> agent.v1.WebrootInfo
	46, // 3: agent.v1.CreateWebrootRequest.fqdns:type_name -> agent.v1.FQDNInfo
	45, // 4: agent.v1.UpdateWebrootRequest.webroot:type_name -> agent.v1.WebrootInfo
	46, // 5: agent.v1.UpdateWebrootRequest.fqdns:type_name -> agent.v1.FQDNInfo
	45, // 6: agent.v1.ConfigureRuntimeRequest.webroot:type_name -> agent.v1.WebrootInfo
	47, // 7: agent.v1.CreateDatabaseRequest.database:type_name -> agent.v1.DatabaseInfo
	48, // 8: agent.v1.CreateDatabaseUserRequest.user:type_name -> agent.v1.DatabaseUserInfo
	48, // 9: agent.v1.UpdateDatabaseUserRequest.user:type_name -> agent.v1.DatabaseUserInfo
	49, // 10: agent.v1.CreateValkeyInstanceRequest.instance:type_name -> agent.v1.ValkeyInstanceInfo
	50, // 11: agent.v1.CreateValkeyUserRequest.user:type_name -> agent.v1.ValkeyUserInfo
	50, // 12: agent.v1.UpdateValkeyUserRequest.user:type_name -> agent.v1.ValkeyUserInfo
	51, // 13: agent.v1.InstallCertificateRequest.certificate:type_name -> agent.v1.CertificateInfo
	0,  // 14: agent.v1.NodeAgent.CreateTenant:input_type -> agent.v1.CreateTenantRequest
	2,  // 15: agent.v1.NodeAgent.UpdateTenant:input_type -> agent.v1.UpdateTenantRequest
	4,  // 16: agent.v1.NodeAgent.SuspendTenant:input_type -> agent.v1.SuspendTenantRequest
	6,  // 17: agent.v1.NodeAgent.UnsuspendTenant:input_type -> agent.v1.UnsuspendTenantRequest
	8,  // 18: agent.v1.NodeAgent.DeleteTenant:input_type -> agent.v1.DeleteTenantRequest
	10, // 19: agent.v1.NodeAgent.CreateWebroot:input_type -> agent.v1.CreateWebrootRequest
	12, // 20: agent.v1.NodeAgent.UpdateWebroot:input_type -> agent.v1.UpdateWebrootRequest
	14, // 21: agent.v1.NodeAgent.DeleteWebroot:input_type -> agent.v1.DeleteWebrootRequest
	16, // 22: agent.v1.NodeAgent.ConfigureRuntime:input_type -> agent.v1.ConfigureRuntimeRequest
	18, // 23: agent.v1.NodeAgent.ReloadNginx:input_type -> agent.v1.ReloadNginxRequest
	20, // 24: agent.v1.NodeAgent.CreateDatabase:input_type -> agent.v1.CreateDatabaseRequest
	22, // 25: agent.v1.NodeAgent.DeleteDatabase:input_type -> agent.v1.DeleteDatabaseRequest
	24, // 26: agent.v1.NodeAgent.CreateDatabaseUser:input_type -> agent.v1.CreateDatabaseUserRequest
	26, // 27: agent.v1.NodeAgent.UpdateDatabaseUser:input_type -> agent.v1.UpdateDatabaseUserRequest
	28, // 28: agent.v1.NodeAgent.DeleteDatabaseUser:input_type -> agent.v1.DeleteDatabaseUserRequest
	30, // 29: agent.v1.NodeAgent.CreateValkeyInstance:input_type -> agent.v1.CreateValkeyInstanceRequest
	32, // 30: agent.v1.NodeAgent.DeleteValkeyInstance:input_type -> agent.v1.DeleteValkeyInstanceRequest
	34, // 31: agent.v1.NodeAgent.CreateValkeyUser:input_type -> agent.v1.CreateValkeyUserRequest
	36, // 32: agent.v1.NodeAgent.UpdateValkeyUser:input_type -> agent.v1.UpdateValkeyUserRequest
	38, // 33: agent.v1.NodeAgent.DeleteValkeyUser:input_type -> agent.v1.DeleteValkeyUserRequest
	40, // 34: agent.v1.NodeAgent.InstallCertificate:input_type -> agent.v1.InstallCertificateRequest
	42, // 35: agent.v1.NodeAgent.HealthCheck:input_type -> agent.v1.HealthCheckRequest
	1,  // 36: agent.v1.NodeAgent.CreateTenant:output_type -> agent.v1.CreateTenantResponse
	3,  // 37: agent.v1.NodeAgent.UpdateTenant:output_type -> agent.v1.UpdateTenantResponse
	5,  // 38: agent.v1.NodeAgent.SuspendTenant:output_type -> agent.v1.SuspendTenantResponse
	7,  // 39: agent.v1.NodeAgent.UnsuspendTenant:output_type -> agent.v1.UnsuspendTenantResponse
	9,  // 40: agent.v1.NodeAgent.DeleteTenant:output_type -> agent.v1.DeleteTenantResponse
	11, // 41: agent.v1.NodeAgent.CreateWebroot:output_type -> agent.v1.CreateWebrootResponse
	13, // 42: agent.v1.NodeAgent.UpdateWebroot:output_type -> agent.v1.UpdateWebrootResponse
	15, // 43: agent.v1.NodeAgent.DeleteWebroot:output_type -> agent.v1.DeleteWebrootResponse
	17, // 44: agent.v1.NodeAgent.ConfigureRuntime:output_type -> agent.v1.ConfigureRuntimeResponse
	19, // 45: agent.v1.NodeAgent.ReloadNginx:output_type -> agent.v1.ReloadNginxResponse
	21, // 46: agent.v1.NodeAgent.CreateDatabase:output_type -> agent.v1.CreateDatabaseResponse
	23, // 47: agent.v1.NodeAgent.DeleteDatabase:output_type -> agent.v1.DeleteDatabaseResponse
	25, // 48: agent.v1.NodeAgent.CreateDatabaseUser:output_type -> agent.v1.CreateDatabaseUserResponse
	27, // 49: agent.v1.NodeAgent.UpdateDatabaseUser:output_type -> agent.v1.UpdateDatabaseUserResponse
	29, // 50: agent.v1.NodeAgent.DeleteDatabaseUser:output_type -> agent.v1.DeleteDatabaseUserResponse
	31, // 51: agent.v1.NodeAgent.CreateValkeyInstance:output_type -> agent.v1.CreateValkeyInstanceResponse
	33, // 52: agent.v1.NodeAgent.DeleteValkeyInstance:output_type -> agent.v1.DeleteValkeyInstanceResponse
	35, // 53: agent.v1.NodeAgent.CreateValkeyUser:output_type -> agent.v1.CreateValkeyUserResponse
	37, // 54: agent.v1.NodeAgent.UpdateValkeyUser:output_type -> agent.v1.UpdateValkeyUserResponse
	39, // 55: agent.v1.NodeAgent.DeleteValkeyUser:output_type -> agent.v1.DeleteValkeyUserResponse
	41, // 56: agent.v1.NodeAgent.InstallCertificate:output_type -> agent.v1.InstallCertificateResponse
	43, // 57: agent.v1.NodeAgent.HealthCheck:output_type -> agent.v1.HealthCheckResponse
	36, // [36:58] is the sub-list for method output_type
	14, // [14:36] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_agent_v1_agent_proto_init() }
func file_agent_v1_agent_proto_init() {
	if File_agent_v1_agent_proto != nil {
		return
	}
	file_agent_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   44,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_agent_v1_agent_proto = out.File
	file_agent_v1_agent_proto_goTypes = nil
	file_agent_v1_agent_proto_depIdxs = nil
}
