// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: agent/v1/types.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TenantInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Uid           int32                  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	SftpEnabled   bool                   `protobuf:"varint,4,opt,name=sftp_enabled,json=sftpEnabled,proto3" json:"sftp_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantInfo) Reset() {
	*x = TenantInfo{}
	mi := &file_agent_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantInfo) ProtoMessage() {}

func (x *TenantInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantInfo.ProtoReflect.Descriptor instead.
func (*TenantInfo) Descriptor() ([]byte, []int) {
	return file_agent_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *TenantInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TenantInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TenantInfo) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *TenantInfo) GetSftpEnabled() bool {
	if x != nil {
		return x.SftpEnabled
	}
	return false
}

type WebrootInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantName     string                 `protobuf:"bytes,2,opt,name=tenant_name,json=tenantName,proto3" json:"tenant_name,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Runtime        string                 `protobuf:"bytes,4,opt,name=runtime,proto3" json:"runtime,omitempty"`
	RuntimeVersion string                 `protobuf:"bytes,5,opt,name=runtime_version,json=runtimeVersion,proto3" json:"runtime_version,omitempty"`
	RuntimeConfig  string                 `protobuf:"bytes,6,opt,name=runtime_config,json=runtimeConfig,proto3" json:"runtime_config,omitempty"` // JSON string
	PublicFolder   string                 `protobuf:"bytes,7,opt,name=public_folder,json=publicFolder,proto3" json:"public_folder,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WebrootInfo) Reset() {
	*x = WebrootInfo{}
	mi := &file_agent_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebrootInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebrootInfo) ProtoMessage() {}

func (x *WebrootInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebrootInfo.ProtoReflect.Descriptor instead.
func (*WebrootInfo) Descriptor() ([]byte, []int) {
	return file_agent_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *WebrootInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WebrootInfo) GetTenantName() string {
	if x != nil {
		return x.TenantName
	}
	return ""
}

func (x *WebrootInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WebrootInfo) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *WebrootInfo) GetRuntimeVersion() string {
	if x != nil {
		return x.RuntimeVersion
	}
	return ""
}

func (x *WebrootInfo) GetRuntimeConfig() string {
	if x != nil {
		return x.RuntimeConfig
	}
	return ""
}

func (x *WebrootInfo) GetPublicFolder() string {
	if x != nil {
		return x.PublicFolder
	}
	return ""
}

type FQDNInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fqdn          string                 `protobuf:"bytes,1,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	WebrootId     string                 `protobuf:"bytes,2,opt,name=webroot_id,json=webrootId,proto3" json:"webroot_id,omitempty"`
	SslEnabled    bool                   `protobuf:"varint,3,opt,name=ssl_enabled,json=sslEnabled,proto3" json:"ssl_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FQDNInfo) Reset() {
	*x = FQDNInfo{}
	mi := &file_agent_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FQDNInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FQDNInfo) ProtoMessage() {}

func (x *FQDNInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FQDNInfo.ProtoReflect.Descriptor instead.
func (*FQDNInfo) Descriptor() ([]byte, []int) {
	return file_agent_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *FQDNInfo) GetFqdn() string {
	if x != nil {
		return x.Fqdn
	}
	return ""
}

func (x *FQDNInfo) GetWebrootId() string {
	if x != nil {
		return x.WebrootId
	}
	return ""
}

func (x *FQDNInfo) GetSslEnabled() bool {
	if x != nil {
		return x.SslEnabled
	}
	return false
}

type CertificateInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fqdn          string                 `protobuf:"bytes,1,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	CertPem       string                 `protobuf:"bytes,2,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	KeyPem        string                 `protobuf:"bytes,3,opt,name=key_pem,json=keyPem,proto3" json:"key_pem,omitempty"`
	ChainPem      string                 `protobuf:"bytes,4,opt,name=chain_pem,json=chainPem,proto3" json:"chain_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateInfo) Reset() {
	*x = CertificateInfo{}
	mi := &file_agent_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateInfo) ProtoMessage() {}

func (x *CertificateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateInfo.ProtoReflect.Descriptor instead.
func (*CertificateInfo) Descriptor() ([]byte, []int) {
	return file_agent_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *CertificateInfo) GetFqdn() string {
	if x != nil {
		return x.Fqdn
	}
	return ""
}

func (x *CertificateInfo) GetCertPem() string {
	if x != nil {
		return x.CertPem
	}
	return ""
}

func (x *CertificateInfo) GetKeyPem() string {
	if x != nil {
		return x.KeyPem
	}
	return ""
}

func (x *CertificateInfo) GetChainPem() string {
	if x != nil {
		return x.ChainPem
	}
	return ""
}

type DatabaseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseInfo) Reset() {
	*x = DatabaseInfo{}
	mi := &file_agent_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseInfo) ProtoMessage() {}

func (x *DatabaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseInfo.ProtoReflect.Descriptor instead.
func (*DatabaseInfo) Descriptor() ([]byte, []int) {
	return file_agent_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *DatabaseInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DatabaseUserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseName  string                 `protobuf:"bytes,1,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Privileges    []string               `protobuf:"bytes,4,rep,name=privileges,proto3" json:"privileges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseUserInfo) Reset() {
	*x = DatabaseUserInfo{}
	mi := &file_agent_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseUserInfo) ProtoMessage() {}

func (x *DatabaseUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseUserInfo.ProtoReflect.Descriptor instead.
func (*DatabaseUserInfo) Descriptor() ([]byte, []int) {
	return file_agent_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *DatabaseUserInfo) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *DatabaseUserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DatabaseUserInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DatabaseUserInfo) GetPrivileges() []string {
	if x != nil {
		return x.Privileges
	}
	return nil
}

type ValkeyInstanceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	MaxMemoryMb   int32                  `protobuf:"varint,4,opt,name=max_memory_mb,json=maxMemoryMb,proto3" json:"max_memory_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValkeyInstanceInfo) Reset() {
	*x = ValkeyInstanceInfo{}
	mi := &file_agent_v1_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValkeyInstanceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValkeyInstanceInfo) ProtoMessage() {}

func (x *ValkeyInstanceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValkeyInstanceInfo.ProtoReflect.Descriptor instead.
func (*ValkeyInstanceInfo) Descriptor() ([]byte, []int) {
	return file_agent_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *ValkeyInstanceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ValkeyInstanceInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ValkeyInstanceInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ValkeyInstanceInfo) GetMaxMemoryMb() int32 {
	if x != nil {
		return x.MaxMemoryMb
	}
	return 0
}

type ValkeyUserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceName  string                 `protobuf:"bytes,1,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Privileges    []string               `protobuf:"bytes,5,rep,name=privileges,proto3" json:"privileges,omitempty"`
	KeyPattern    string                 `protobuf:"bytes,6,opt,name=key_pattern,json=keyPattern,proto3" json:"key_pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValkeyUserInfo) Reset() {
	*x = ValkeyUserInfo{}
	mi := &file_agent_v1_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValkeyUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValkeyUserInfo) ProtoMessage() {}

func (x *ValkeyUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValkeyUserInfo.ProtoReflect.Descriptor instead.
func (*ValkeyUserInfo) Descriptor() ([]byte, []int) {
	return file_agent_v1_types_proto_rawDescGZIP(), []int{7}
}

func (x *ValkeyUserInfo) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *ValkeyUserInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ValkeyUserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ValkeyUserInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ValkeyUserInfo) GetPrivileges() []string {
	if x != nil {
		return x.Privileges
	}
	return nil
}

func (x *ValkeyUserInfo) GetKeyPattern() string {
	if x != nil {
		return x.KeyPattern
	}
	return ""
}

var File_agent_v1_types_proto protoreflect.FileDescriptor

const file_agent_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x14agent/v1/types.proto\x12\bagent.v1\"e\n" +
	"\n" +
	"TenantInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\x05R\x03uid\x12!\n" +
	"\fsftp_enabled\x18\x04 \x01(\bR\vsftpEnabled\"\xe1\x01\n" +
	"\vWebrootInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vtenant_name\x18\x02 \x01(\tR\n" +
	"tenantName\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aruntime\x18\x04 \x01(\tR\aruntime\x12'\n" +
	"\x0fruntime_version\x18\x05 \x01(\tR\x0eruntimeVersion\x12%\n" +
	"\x0eruntime_config\x18\x06 \x01(\tR\rruntimeConfig\x12#\n" +
	"\rpublic_folder\x18\a \x01(\tR\fpublicFolder\"^\n" +
	"\bFQDNInfo\x12\x12\n" +
	"\x04fqdn\x18\x01 \x01(\tR\x04fqdn\x12\x1d\n" +
	"\n" +
	"webroot_id\x18\x02 \x01(\tR\twebrootId\x12\x1f\n" +
	"\vssl_enabled\x18\x03 \x01(\bR\n" +
	"sslEnabled\"v\n" +
	"\x0fCertificateInfo\x12\x12\n" +
	"\x04fqdn\x18\x01 \x01(\tR\x04fqdn\x12\x19\n" +
	"\bcert_pem\x18\x02 \x01(\tR\acertPem\x12\x17\n" +
	"\akey_pem\x18\x03 \x01(\tR\x06keyPem\x12\x1b\n" +
	"\tchain_pem\x18\x04 \x01(\tR\bchainPem\"\"\n" +
	"\fDatabaseInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x8f\x01\n" +
	"\x10DatabaseUserInfo\x12#\n" +
	"\rdatabase_name\x18\x01 \x01(\tR\fdatabaseName\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1e\n" +
	"\n" +
	"privileges\x18\x04 \x03(\tR\n" +
	"privileges\"|\n" +
	"\x12ValkeyInstanceInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\"\n" +
	"\rmax_memory_mb\x18\x04 \x01(\x05R\vmaxMemoryMb\"\xc2\x01\n" +
	"\x0eValkeyUserInfo\x12#\n" +
	"\rinstance_name\x18\x01 \x01(\tR\finstanceName\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x1e\n" +
	"\n" +
	"privileges\x18\x05 \x03(\tR\n" +
	"privileges\x12\x1f\n" +
	"\vkey_pattern\x18\x06 \x01(\tR\n" +
	"keyPatternB1Z/github.com/edvin/hosting/proto/agent/v1;agentv1b\x06proto3"

var (
	file_agent_v1_types_proto_rawDescOnce sync.Once
	file_agent_v1_types_proto_rawDescData []byte
)

func file_agent_v1_types_proto_rawDescGZIP() []byte {
	file_agent_v1_types_proto_rawDescOnce.Do(func() {
		file_agent_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_types_proto_rawDesc), len(file_agent_v1_types_proto_rawDesc)))
	})
	return file_agent_v1_types_proto_rawDescData
}

var file_agent_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_agent_v1_types_proto_goTypes = []any{
	(*TenantInfo)(nil),         // 0: agent.v1.TenantInfo
	(*WebrootInfo)(nil),        // 1: agent.v1.WebrootInfo
	(*FQDNInfo)(nil),           // 2: agent.v1.FQDNInfo
	(*CertificateInfo)(nil),    // 3: agent.v1.CertificateInfo
	(*DatabaseInfo)(nil),       // 4: agent.v1.DatabaseInfo
	(*DatabaseUserInfo)(nil),   // 5: agent.v1.DatabaseUserInfo
	(*ValkeyInstanceInfo)(nil), // 6: agent.v1.ValkeyInstanceInfo
	(*ValkeyUserInfo)(nil),     // 7: agent.v1.ValkeyUserInfo
}
var file_agent_v1_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agent_v1_types_proto_init() }
func file_agent_v1_types_proto_init() {
	if File_agent_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_types_proto_rawDesc), len(file_agent_v1_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agent_v1_types_proto_goTypes,
		DependencyIndexes: file_agent_v1_types_proto_depIdxs,
		MessageInfos:      file_agent_v1_types_proto_msgTypes,
	}.Build()
	File_agent_v1_types_proto = out.File
	file_agent_v1_types_proto_goTypes = nil
	file_agent_v1_types_proto_depIdxs = nil
}
